const IMAGES = {
  LOAD: 'IMAGES_LOAD',
  LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
  LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

const VENUE = {
  VENUE_RATE: 'RATE_VENUE',
  VENUE_FETCH: 'FETCH_VENUES',
  VENUE_FETCHED: 'FETCHED_VENUES',
  VENUE_REVIEW: 'REVIEW_VENUE',
  FILTER_VENUES_LIST: 'FILTER_VENUE',
  LOAD_FAILED: 'LOAD_FAILED',
};

export {IMAGES, VENUE};
